=== afrittoli/cdevents-sdk-go/pkg/api/tests/schemas/foosubjectbarpredicate.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://cdevents.dev/0.2.0/schema/foosubject-barpredicate-event",
	"properties": {
	  "context": {
		"properties": {
		  "version": {
			"type": "string",
			"minLength": 1
		  },
		  "id": {
			"type": "string",
			"minLength": 1
		  },
		  "source": {
			"type": "string",
			"minLength": 1,
			"format": "uri-reference"
		  },
		  "type": {
			"type": "string",
			"enum": [
			  "dev.cdevents.foosubject.barpredicate.1.2.3"
			],
			"default": "dev.cdevents.foosubject.barpredicate.1.2.3"
		  },
		  "timestamp": {
			"type": "string",
			"format": "date-time"
		  }
		},
		"additionalProperties": false,
		"type": "object",
		"required": [
		  "version",
		  "id",
		  "source",
		  "type",
		  "timestamp"
		]
	  },
	  "subject": {
		"properties": {
		  "id": {
			"type": "string",
			"minLength": 1
		  },
		  "source": {
			"type": "string",
			"minLength": 1,
			"format": "uri-reference"
		  },
		  "type": {
			"type": "string",
			"minLength": 1,
			"enum": [
			  "fooSubject"
			],
			"default": "fooSubject"
		  },
		  "content": {
			"properties": {
			  "plainField": {
				"type": "string",
				"minLength": 1
			  },
			  "referenceField": {
				"properties": {
				  "id": {
					"type": "string",
					"minLength": 1
				  },
				  "source": {
					"type": "string",
					"minLength": 1,
					"format": "uri-reference"
				  }
				},
				"additionalProperties": false,
				"type": "object",
				"required": [
				  "id"
				]
			  },
			  "artifactId": {
				"type": "string"
			  },
			  "objectField": {
				"properties": {
				  "required": {
					"type": "string",
					"minLength": 1
				  },
				  "optional": {
					"type": "string",
					"format": "uri-reference"
				  }
				},
				"additionalProperties": false,
				"type": "object",
				"required": [
				  "required"
				]
			  }
			},
			"additionalProperties": false,
			"type": "object",
			"required": [
			  "plainField",
			  "referenceField"
			]
		  }
		},
		"additionalProperties": false,
		"type": "object",
		"required": [
		  "id",
		  "type",
		  "content"
		]
	  },
	  "customData": {
		"oneOf": [
		  {
			"type": "object"
		  },
		  {
			"type": "string",
			"contentEncoding": "base64"
		  }
		]
	  },
	  "customDataContentType": {
		"type": "string"
	  }
	},
	"additionalProperties": false,
	"type": "object",
	"required": [
	  "context",
	  "subject"
	]
}

=== afrittoli/cdevents-sdk-go/pkg/api/tests/examples/non_json_custom_data.json
{
	"context": {
		"version": "0.3.0",
		"id": "271069a8-fc18-44f1-b38f-9d70a1695819",
		"source": "/event/source/123",
		"type": "dev.cdevents.foosubject.barpredicate.1.2.3",
		"timestamp": "2023-03-20T14:27:05.315384Z"
	},
	"subject": {
		"id": "mySubject123",
		"source": "/event/source/123",
		"type": "fooSubject",
		"content": {
			"referenceField": {
				"id": "myChange123"
			},
			"artifactId": "pkg:oci/myapp@sha256%3A0b31b1c02ff458ad9b7b81cbdf8f028bd54699fa151f221d1e8de6817db93427",
			"plainField": "testValue",
			"objectField": {
				"required": "myChange123",
				"optional": "/event/source/123"
			}
		}
	},
	"customData": "PHhtbD50ZXN0RGF0YTwveG1sPg==",
	"customDataContentType": "application/xml"
}
